Update private changed for liveview 0.19.0
BartOtten/phoenix_live_head pull request #9
Opened 2023-06-21 12:12 UTC by dfalling

This resolves the incompatibility introduced in LiveView 0.19.0.

Closes #8

2023-06-21 12:12 UTC, dfalling commented on mix.exs
> +      {:phoenix_live_view, ">= 0.19.0"},
This version will not work in previous versions of LiveView, so I had to bump the minimum version up.

2023-06-22 09:32 UTC, BartOtten requested changes
Thanks for not only reporting the issue but also create a PR to resolve it. Have included a suggestion to not need a version bump.

2023-06-22 09:32 UTC, BartOtten commented on lib/live_head.ex
> +      put_in(socket.private.__temp__.push_events, events)
I think we can make the fix without needing a version bump by detecting which field is supported. Could you have a try with something like:

```elixir
cond do
  # Phoenix LiveView < 0.19
  merged? && Map.has_key?(socket.private, :__changed__) ->
    put_in(socket.private.__changed__.push_events, events)
  
  # Phoenix LiveView >= 0.19
  merged? -> 
    put_in(socket.private.__temp__.push_events, events)
    
  true -> 
    push_event(socket, "hd", %{c: [[query, [change]]]})
end
```

2023-06-22 12:00 UTC, dfalling commented on lib/live_head.ex
> +      put_in(socket.private.__temp__.push_events, events)
Nice, that's much better than restricting the LiveView version. I tweaked the comments a bit as well.

2023-06-23 08:53 UTC, BartOtten approved these changes, later dismissed

2023-06-23 10:27 UTC, dfalling commented
The new logic pushed us over Credo's complexity limit. Any preference on how to resolve this? Maybe splitting the logic to find the `{events, merged?}` out to a separate helper function?

2023-06-30 09:21 UTC, BartOtten commented
Hi @dfalling,

I think we can resolve it indeed by extracting some private helper functions.

```
  defp put_event(socket, events) when is_map_key(socket.private, :__changed__)
  defp put_event(socket, events) when is_map_key(socket.private, :__temp__)
```
    
And the event reducer too.
    
```
  defp event_reducer(["hd", %{c: changes}], _merged?, query, change),
     do:  {["hd", %{c: push_or_merge_head_change(changes, query, change)}], true}

  defp event_reducer(event, merged?, _query, _change), 
      do: {event, merged?}

```

Could you give it a try? :)

2023-06-30 14:12 UTC, BartOtten approved these changes

2023-06-30 14:35 UTC, merged

2023-06-30 15:54 UTC, BartOtten commented
@dfalling Thanks for your contribution!

2023-06-30 17:21 UTC, dfalling commented
Sure thing, thanks for the great lib!